import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './UseCases.css';
import imgBus from '../assets/bus-stop.png';
import imgVape from '../assets/adptado.png';
import imgEmergency from '../assets/emergencia.png';
const UseCases = () => {
    return (_jsx("section", { className: "usecases-section", id: "usecases", children: _jsxs("div", { className: "usecases-container", children: [_jsx("h2", { children: "Casos de Uso" }), _jsx("p", { className: "usecases-intro", children: "O Enervape Charger foi projetado para reaproveitar vapes descart\u00E1veis como fonte de energia limpa e acess\u00EDvel, oferecendo solu\u00E7\u00F5es sustent\u00E1veis em locais p\u00FAblicos com pouco acesso \u00E0 energia el\u00E9trica." }), _jsxs("div", { className: "usecases-cards", children: [_jsxs("div", { className: "usecase-card", children: [_jsx("img", { src: imgBus, alt: "Aproveitamento de materiais", className: "usecase-image" }), _jsxs("div", { className: "usecase-content", children: [_jsx("div", { className: "usecase-number", children: "1" }), _jsx("h3", { children: "Aproveitamento de materiais" }), _jsx("p", { children: "Vapes descart\u00E1veis s\u00E3o transformados em carregadores solares port\u00E1teis, prolongando sua vida \u00FAtil e reduzindo o lixo eletr\u00F4nico." })] })] }), _jsxs("div", { className: "usecase-card", children: [_jsx("img", { src: imgVape, alt: "Design adaptativo", className: "usecase-image" }), _jsxs("div", { className: "usecase-content", children: [_jsx("div", { className: "usecase-number", children: "2" }), _jsx("h3", { children: "Design adaptativo" }), _jsx("p", { children: "Os dispositivos foram adaptados para serem compactos, eficientes e compat\u00EDveis com diferentes necessidades de uso." })] })] }), _jsxs("div", { className: "usecase-card", children: [_jsx("img", { src: imgEmergency, alt: "Emerg\u00EAncia e Continuidade", className: "usecase-image" }), _jsxs("div", { className: "usecase-content", children: [_jsx("div", { className: "usecase-number", children: "3" }), _jsx("h3", { children: "Emerg\u00EAncia e Continuidade" }), _jsx("p", { children: "Oferecem uma fonte alternativa de energia em situa\u00E7\u00F5es de emerg\u00EAncia, como quedas de energia ou locais remotos." })] })] })] })] }) }));
};
export default UseCases;
